# miasma engine config

[assets]
assetTexturesRoot = "./resources/textures"
assetShadersRoot = "./resources/shaders"
assetModelsRoot = "./resources/models"
assetMaterialsRoot = "./resources/materials"

[scenes]
startup = "SandboxScene"
